name: FMP

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7.*
  - pip=19.2.*
  - numpy=1.17.*
  - scipy=1.3.*
  - matplotlib=3.1.*
  - ipython=7.8.*
  - jupyter=1.0.*
  - pandas=1.0.*
  - scikit-learn=0.21.*
  - ffmpeg=4.2.*
  - numba=0.51.*
  - jupyter_contrib_nbextensions=0.5.*
  - jupyter_client=6.1.*
  - pip:
    - mir-eval==0.5.*
    - nbstripout==0.3.*
    - music21==5.7.*
    - pretty_midi==0.2.*
    - librosa==0.8.*
    - soundfile==0.9.*
    - resampy==0.2.*
